spring:
  application:
    name: product-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: Product Service

server:
  port: 9877

logging:
  level:
    root: off
    com.ozgurbaybas: DEBUG
---
spring:
  profiles: localhost
  cloud:
    config:
      uri: http://localhost:9877
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSqlDialect
    properties:
      hibernate:
        default_schema: stock_management

  datasource:
    url: "jdbc:postgresql://localhost:5432/stock_management"
    username: root
    password: root